FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ ./
# 执行构建命令，这会在 /app/dist 目录下生成静态文件
RUN npm run build
# 使用一个轻量的 Nginx 官方镜像
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

# COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80